In [ ]:
!pip install transformers datasets accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.9.0+cpu)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.11.12)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Data set/ai-medical-chatbot[1].csv")

In [ ]:
df.head(6)

,Description,Patient,Doctor
0,Q. What does abutment of the nerve root mean?,"Hi doctor,I am just wondering what is abutting...",Hi. I have gone through your query with dilige...
1,Q. What should I do to reduce my weight gained...,"Hi doctor, I am a 22-year-old female who was d...",Hi. You have really done well with the hypothy...
2,Q. I have started to get lots of acne on my fa...,Hi doctor! I used to have clear skin but since...,Hi there Acne has multifactorial etiology. Onl...
3,Q. Why do I have uncomfortable feeling between...,"Hello doctor,I am having an uncomfortable feel...",Hello. The popping and discomfort what you fel...
4,Q. My symptoms after intercourse threatns me e...,"Hello doctor,Before two years had sex with a c...",Hello. The HIV test uses a finger prick blood ...
5,Q. I had a surgery which ended up with some fa...,"Hello doctor,I had an emergency surgery six mo...",Hello. If you are saying it is already six mon...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256916 entries, 0 to 256915
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Description  256916 non-null  object
 1   Patient      256916 non-null  object
 2   Doctor       256916 non-null  object
dtypes: object(3)
memory usage: 5.9+ MB

In [ ]:
df.describe()

,Description,Patient,Doctor
count,256916,256916,256916
unique,228722,246006,242150
top,Q. Why do periods get delayed after first time...,"Hello doctor, My fiancee and I had unprotected...",Hi. For further doubts consult a sexologist on...
freq,1137,1137,1519

In [ ]:
df.isnull().sum()

Description    0
Patient        0
Doctor         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(10378)

In [ ]:
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

In [ ]:
#Prepare Conversation Format (Patient ↔ Doctor)

In [ ]:
def prepared_conversation_between_doctor_and_patient(row):
    patient_question = "## Patient: " + row["Description"].strip()
    doctor_answer = "## Doctor: " + row["Doctor"].strip()
    conversation = {
        "patient_question" : patient_question,
        "doctor_answer" : doctor_answer
    }
    return conversation

In [ ]:
conversations = df.apply(prepared_conversation_between_doctor_and_patient, axis=1)
print("Number of Conversations between Doctor and Patients: ", len(conversations))

Number of Conversations between Doctor and Patients:  246538

In [ ]:
conversations.iloc[0]

{'patient_question': '## Patient: Q. What does abutment of the nerve root mean?',
 'doctor_answer': '## Doctor: Hi. I have gone through your query with diligence and would like you to know that I am here to help you. For further information consult a neurologist online -->'}

In [ ]:
conversations.tolist()[:20]

[{'patient_question': '## Patient: Q. What does abutment of the nerve root mean?',
  'doctor_answer': '## Doctor: Hi. I have gone through your query with diligence and would like you to know that I am here to help you. For further information consult a neurologist online -->'},
 {'patient_question': '## Patient: Q. What should I do to reduce my weight gained due to genetic hypothyroidism?',
  'doctor_answer': '## Doctor: Hi. You have really done well with the hypothyroidism problem. Your levels are normal with less medications which are very good. As it is genetically induced, it is very difficult to lose weight. My advice to you is, you should focus on maintaining normal levels of TSH (thyroid-stimulating hormone) and try to remain active, having a positive outlook in life. Or else, it will become very difficult to balance your life with the symptoms of hypothyroidism. Even though your weight has not reduced, be very careful in not putting on weight here afterward. Everyday brisk walking for 1 hour. If you have body pain, alternate with exercises and walking. Avoid all kinds of junk foods, processed, bakery products, rich sweets, fatty foods, sodas, alcohol, and smoking. Avoid partying and binge eating. Follow the food timings properly. Have small frequent meals. In between snacks should be strictly fruits or any kind of low-calorie foods. Have unsalted nuts around five daily. It can give a glow to your dry skin. Everyday water intake should be around 1.5-2 liters. You can use flax seeds. Powder it and mix it in your food. It is a fiber which will give you fullness. Use turmeric, fenugreek seeds, or powder every day. It is a good antioxidant and fenugreek helps in reducing cholesterol levels. Include low-fat milk, curd every day. Egg white, lean chicken, or fish can be taken daily in moderation (anyone). Organ meats need to be avoided. Is your menstrual cycle normal? Please get back if you have any other complaints. Follow up after 15 days.'},
 {'patient_question': '## Patient: Q. I have started to get lots of acne on my face, particularly on my forehead. Please help me.',
  'doctor_answer': '## Doctor: Hi there Acne has multifactorial etiology. Only acne soap does not improve if ypu have grade 2 or more grade acne. You need to have oral and topical medications. This before writing medicines i need to confirm your grade of acne. For mild grade topical clindamycin or retenoic acud derivative would suffice whereas for higher grade acne you need oral medicines aluke doxycycline azithromycin or isotretinoin. Acne vulgaris Cleansing face with antiacne face wash'},
 {'patient_question': '## Patient: Q. Why do I have uncomfortable feeling between the middle of my spine and left shoulder blade?',
  'doctor_answer': '## Doctor: Hello. The popping and discomfort what you felt is either because of improper scapulothoracic mobility or may be due to facet joint irritation in the neck with intervertebral hypermobility. Which could have caused due to stiffness in the chest muscles, shoulder stiffness, etc.  I would recommend you to do a lot of icing in the chest and back muscles. Maintain your neck and upper back posture by doing some back retraction work. Gently stretch your neck and chest. Gently massage your chest and shoulders to relieve tension in the muscles. I hope this is helpful for now. Kindly revert in case you need any help in this regard.'},
 {'patient_question': '## Patient: Q. My symptoms after intercourse threatns me even after having negative HIV result. Kindly help.',
  'doctor_answer': '## Doctor: Hello. The HIV test uses a finger prick blood sample, with results given within 20 minutes, and is 99 % accurate at detecting any HIV exposure that may have occurred more than 12 weeks ago. However, it can potentially pick up HIV infection from as little as four weeks ago. There is nothing to worry nothing will happen, and please repeat your test after 12 weeks. If you want accurate results to get, it has done RNA PCR which will give actual results within 10days. Antigen detection like P24 gives best results with in two to four weeks. Probably your suffering from a simple viral upper respiratory infection. After 12 weeks, please consult your doctor he will examine and treat you accordingly.'},
 {'patient_question': '## Patient: Q. I had a surgery which ended up with some failures. What can I do to fix it?',
  'doctor_answer': '## Doctor: Hello. If you are saying it is already six months since the surgery and if you are doing regular physiotherapy, still has not gained much of the actions, then it is not worth waiting anymore. There are many muscle transfer surgeries which can give you the desired movements and help you in day today activities. But you have to remember that post such operations you will require time to train the brain and get the full use of such movements. That will take time. Do not want to demotivate you, but tremendous training and hard work might be required to reach the pre trauma stage of your boxing.'},
 {'patient_question': '## Patient: Q. Kindly explain about Beta Strep.',
  'doctor_answer': '## Doctor: Hello. There are lots of bacteria and other organisms that colonize healthy skin. Yeast a fungus also is a commensal in our body. Just the presence of these organisms is of no significance. The colony count is needed, which is high, will need a course of antibiotics, which can be decided by culture and sensitivity. But after a surgery like what you had, or any significant stress or use of lots of antibiotics (as would have happened after surgery) or use of steroids or diabetes, all infections show an altered balance between good and bad bacteria. You do not need any treatment for this. Just wait for your body to develop those good bacteria, and gradually, all tests will come negative. If you have any symptoms, treat as per need. Avoid unnecessary antibiotics use. They will further delay the recovery. I hope I have clarified your query, do write back if any more questions.'},
 {'patient_question': '## Patient: Q. Kindly suggest a homeopathic medicine to stop hairfall and promote hair growth.',
  'doctor_answer': '## Doctor: Hello. I checked the attached photo (attachment removed to protect patient identity) and read your description. It seems you have been suffering from hair loss problem for a longtime. Do you eat healthy food like vegetables and fruits every day? Sometimes lack of nutrition is also the reason for hair loss. Do you know if your father also differed from hair loss issue at this young age? Did you suffer from severe health issues or chronic illnesses? If you do not think above mentioned is the cause for your hair fall, then the only reason I can think is that you have been going through severe stress which has taken a toll on your health. Homeopathy would be a good option in this case as it will cure our problem from the root cause, and there will be no side effects. So to prescribe you a correct homeopathic remedy I need to understand your mental, emotional, and physical state. He ce I need detail case history which can be done either through face to face consultation or online consultation. I would advise you to visit a good homeopath for consultation. For the time being, you can apply arnica hair oil twice a week on your hair. Just mix one spoon of Arnica oil with five spoons of coconut oil and apply all over your scalp. You can gently massage your ear with this mixture. Try this for 15 days and then let me know how you feel. I hope you start feeling better. Let me know if you have any questions.'},
 {'patient_question': '## Patient: Q. Will Nano-Leo give permanent solution for erection problem?',
  'doctor_answer': '## Doctor: Hi. For further doubts consult a sexologist online -->'},
 {'patient_question': '## Patient: Q. Every time I eat spicy food, I poop blood. Why?',
  'doctor_answer': '## Doctor: Hello. I have gone through your information and test reports (attachment removed to protect patient identity). So, in view of that, there are a couple of things that I can opine upon: Hope that helps. For more information consult a general surgeon online -->'},
 {'patient_question': '## Patient: Q. Will Kalarchikai cure multiple ovarian cysts in PCOD?',
  'doctor_answer': '## Doctor: Hello. I just read your query. See Kalarachi Kai choornam is helpful in amenorrhea. As far as small cysts are concerned they are unmatured eggs which failed to induce menstrual cycle previously, as a result, they got collected in the ovary and they will remain in the ovary. Now, you have got your periods you can start trying for conception. But I advise you to do it under the supervision of a nearby gynecologist because egg size is important while conception and that you can know by ovulation study. Ovulation study is performed under the supervision of a gynecologist. For gall stones, surgical intervention is required generally. Medicine is not of much help.'},
 {'patient_question': '## Patient: Q. I masturbate only by rubbing the tip of the penis. Is it a wrong way?',
  'doctor_answer': '## Doctor: Hi. For further doubts consult a sexologist online -->'},
 {'patient_question': '## Patient: Q. I have stomach pain and bloating after taking Augmentin 625. Why?',
  'doctor_answer': '## Doctor: Hello. I welcome you to icliniq. Well it is not uncommon to have Gastric upsets after a course of antibiotic. And antibiotic like augmentin are notorious to cause this. This occur secondary to effect of augmentin on decreasing the amount of lactobacillus microorganism which are normally present in the human gut and help digest the food. You should take yougurt, Kefir (fermented yougurt), Kefir. and there are certain diets with probiotic activity you can start taking it. Plus take Tab Ecotec twice daily for 4 weeks, and Tab Levosulpiride 75 mg once daily half hour before meals.for 2 weeks. You can continue with acinil O syp. while rest of your current medication can be stopped. I hope this will correct your microbiota and will bring the same healthiness as before. good day Antibiotic induced dysbiosis Small intestinal bacterial overgrowth Antibiotic induced dysbiosis Let me know in one week time how you respond to above regimen, if persistent of symptoms I would consider testing and giving some safe antibiotic therapy for 2 weeks.'},
 {'patient_question': '## Patient: Q. Can a painless tooth be extracted since it has a hole in it?',
  'doctor_answer': '## Doctor: Hello. I had gone through your question, and I can understand your concern. If the pain occurs only when you eat food and it gets stuck into it, it is reversible pulpitis. For that, you do not need to get it extracted. You need to get it filled, and it will cost you less than that of pulling (extraction). Second, you will save your tooth too. My suggestion is to get dental filling done as soon as possible. If you want to get it removed, you need to visit a doctor (dentist), and there will be no pain because during extraction local anesthesia is given.'},
 {'patient_question': '## Patient: Q. What does the darker pigmentation at the armpits indicate?',
  'doctor_answer': '## Doctor: Hello. I understand your concern. The pictures are a bit hazy. But from the given images, it looks like a fungal infection by the name of pityriasis versicolor. I would also need to see your chest, upper back, and shoulders to be sure. Kindly send clear photos of the same to make a conclusive diagnosis. Meanwhile, you can start using the following medicines. 1. Tab Fluconazole 400 mg start and repeat once after a week. 2. 2 % Ketoconazole lotion apply for 5-7 mins and wash off once a day.'},
 {'patient_question': '## Patient: Q. I get fever during rainy and winter season. Why?',
  'doctor_answer': '## Doctor: Hello. I need to know a few things, 1. Do you feel feverish, or does the thermometer record a temperature? 2. What other symptoms do you get? Runny or blocked nose, sore throat, throat pain with swallowing, headaches, body pains, etc. 3. Does anyone else around you (family members, co-workers, etc.) develop similar symptoms before or after you do? 4. Do you get any tests done like blood tests or X-rays during those episodes? From your description, it appears that you are getting frequent viral upper respiratory tract infections. These are acquired from other patients through the air (coughing, sneezing, etc.). They are usually short-lived and last no more than five to seven days. Since more than 300 different viruses can cause similar symptoms, you can get infected multiple times each time with a different virus. The same virus cannot affect you again. Unfortunately, antibiotics do not work against viruses. They are meant for bacterial infections only. However, doctors continue to prescribe antibiotics unnecessarily, and this has led to the emergence of widespread bacterial resistance.  Other than symptomatic treatment, no medicine can cure or prevent these infections. They are self-limited, and you will get better even if you do not take any medication. The older you get, the less frequently you will get these infections as your body will be building up defenses with every disease. No household tips or vitamin supplements have been proven to work. Premature birth can lead to increased frequency of infections, but unless the infections are bacterial, not much can be done about them. Please get back to me with answers to the above questions and also attach any test reports you may have.'},
 {'patient_question': '## Patient: Q. Why does one develop swelling after snake bite?',
  'doctor_answer': '## Doctor: Hi. I could understand your crisis. For further information consult a toxicologist online -->'},
 {'patient_question': '## Patient: Q. Why is there a continuous rise in temperature despite taking antibiotics?',
  'doctor_answer': '## Doctor: Hi. I went through your post and investigation (attachment removed to protect patient identity). Regards. For further queries consult an internal medicine physician online -->'},
 {'patient_question': '## Patient: Q. Can my 3 year old son lead a normal life after sepsis?',
  'doctor_answer': '## Doctor: Hello. Regards. For more information consult a paediatrician online -->'},
 {'patient_question': '## Patient: Q. What is the main reason for sepsis in a newborn?',
  'doctor_answer': '## Doctor: Hi. For further information consult a paediatrician online -->'}]

In [ ]:
#Convert Conversations into Hugging Face Dataset

In [ ]:
# convert prepared input (patient questions & doctor ansers ) into datadfame.
from datasets import Dataset

dataset = Dataset.from_list(conversations.tolist())

print("Number of training examples:", len(dataset))
print(dataset[0])

Number of training examples: 246538
{'patient_question': '## Patient: Q. What does abutment of the nerve root mean?', 'doctor_answer': '## Doctor: Hi. I have gone through your query with diligence and would like you to know that I am here to help you. For further information consult a neurologist online -->'}

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments
import transformers
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# Training dataset (80%)
fraction = 0.8
train_size = int(fraction * len(dataset))

train_dataset = dataset.shuffle(seed=42).select(range(train_size))

# Validation dataset (20%)
eval_dataset = dataset.shuffle(seed=42).select(range(train_size, len(dataset)))

In [ ]:
print(f"Train size: {len(train_dataset)}")
print(f"Eval size: {len(eval_dataset)}")

Train size: 197230
Eval size: 49308

In [ ]:
base_model_id = "microsoft/DialoGPT-medium"

tokenizer = AutoTokenizer.from_pretrained(base_model_id)
model = AutoModelForCausalLM.from_pretrained(base_model_id)



tokenizer.pad_token = tokenizer.eos_token

def tokenize_function(conversations):
    texts = [
        patient_question + "\n" + doctor_answer
        for patient_question, doctor_answer in zip(conversations['patient_question'], conversations['doctor_answer'])
    ]
    tokenized_texts = tokenizer(texts, truncation=True, padding="max_length", max_length= 512 )
    tokenized_texts["labels"] = tokenized_texts["input_ids"].copy()
    return tokenized_texts

In [ ]:
# Tokenize the dataset
tokenized_train = train_dataset.map(tokenize_function, batched=True)
tokenized_eval = eval_dataset.map(tokenize_function, batched=True)

# Set format for PyTorch
tokenized_train.set_format("torch")
tokenized_eval.set_format("torch")

NameError: name 'train_dataset' is not defined

In [ ]:
output_dir = "./fine_tuned_medical_chatbot"

training_args = TrainingArguments(
    output_dir=output_dir,
    max_steps=300,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    learning_rate=5e-5,
    weight_decay=0.01,
    fp16=True,
    logging_steps=1,
    save_strategy="steps",
    save_steps=100,
    save_total_limit=2,
    disable_tqdm=False,
    report_to="none",
)

trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = tokenized_train,
    # eval_dataset = tokenized_eval

)

In [ ]:
## enable checkpointing + CUDA memory fix
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
model.gradient_checkpointing_enable()

In [ ]:
print("Starting training...")
trainer.train()
print("Training complete.")

`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...

Starting training...

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Training complete.

In [ ]:
trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)

print("Model and tokenizer saved Successfully.")

In [ ]:
#Reload Fine-Tuned Medical Chatbot Model for Inference
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

model_dir = "/content/drive/MyDrive/Data set/ai-medical-chatbot[1].csv"

# Load model & tokenizer
model = AutoModelForCausalLM.from_pretrained(model_dir)
tokenizer = AutoTokenizer.from_pretrained(model_dir)

# Create a chatbot pipeline
chatbot = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device=0
)

In [ ]:
import torch

def safe_generate(prompt, threshold=0.25):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_length=200,
            output_scores=True,
            return_dict_in_generate=True,
            do_sample=True,
            temperature=0.7,
            top_p=0.9
        )

    scores = outputs.scores  # logits
    probs = [torch.softmax(s, dim=-1).max().item() for s in scores]
    avg_confidence = sum(probs) / len(probs)

    if avg_confidence < threshold:
        return "SORRY I DON'T KNOW"

    text = tokenizer.decode(outputs.sequences[0], skip_special_tokens=True)
    return text.split("Doctor:")[-1].strip()

In [ ]:
prompt = "Patient: What are the symptoms of Lymphocytic Choriomeningitis (LCM)?\nDoctor:"
response = chatbot(prompt, max_length=200, do_sample=True, top_p=0.9, temperature=0.8)

print("Chatbot:", response[0]["generated_text"])